stencila/stencila

- tests/documents/include/default.md
As discussed in https://github.com/stencila/js/issues/2, this updates the include document to use a list syntax.
> use list syntax for includes

- tests/documents/execute/default.html
As discussed in https://github.com/stencila/js/issues/2#issuecomment-280496250, this adds `code` tags to the expected output of the `execute` module.
> update execute html to use <code> tag

- src/host/Host.js
This should fix the error that @michael was experiencing when attempting to use external languages in Docker containers. I have tested it locally and it fixes that problem for me. Could you please test before we release a patch.
There is one new dev setup step when wanting to test this in the desktop - related to our new linear dependencies stencila -> node -> desktop. I'll add something to desktop README about that.
More generally, we need some integration tests to catch this type of small but Very Bad™ bug. I'll set up a separate pull request for that.
> Fix bug which caused only the first peer to be checked

- .travis.yml
- Makefile
- README.md
- examples/document/app.js
- make.js
- package.json
- src/document/DocumentEditor.js
- src/document/DocumentPage.js
- src/util/requests.js
- tests/documents/external-language-cells.html
- tests/integration.sh
- tools/runner.js
`tools/runner.js` is a Node.js script for running Stencila documents to check for errors. It is intended to be used for integration tests within this repo but also for testing a document's "reproducibility" and "CI for documents" at http://open.stenci.la
The `tests/integration.sh` uses `runner.js` to do integration tests. The current tests in there should have caught the bug @michael recently found.
@michael and @oliver---- : could you review, in particular:
- commit 2a51afd moves CellEngine - which seems to be OK but may have unseen side effects
- currently runner waits one second for all cells to execute, but ideally it would just wait for a 'finished' signal from the document
> Introduce tools/runner.js and integration tests

- .travis.yml
- Makefile
- README.md
This PR archives each build to http://builds.stenci.la/stencila/. The primary purpose of this is to be able to provide tests users with links to WIP UIs without them having to clone the repo and run a dev setup. It also provides a readily accessible archive of build which could be useful if we want quickly go back and compare previous UIs.
We might build off this in the future to provide "demo" site that links to the most recent **release** build.
@michael and @oliver---- : could you review, and if OK merge. And if not make changes :)
> Archiving of builds

- package.json
- src/document/nodes/cell/CellHTMLConverter.js
- tools/runner.js
Document cells export their value and runner creates a document digest.
These changes allow us to create a digest for each document (pre and post execution) to help in determining if the execution, including the execution environment , has changed. 
This is used in our Docker image shrinking tests to verify that we get the same document reproduced after shrinking an image: https://github.com/stencila/images/blob/master/.test/shrink-alpha-documents/cmd.sh
> Document digest

- src/spreadsheet/SpreadsheetSchema.md
@oliver---- : I've transferred across some of the documentation from the `datatable-schema` branch into a separate `md` file.
The only things missing in the new RNG from that old branch at this stage are:
-  `name` (restricted to alpha-numeric and underscores?) , `title` (a more readable name) and `description` attributes for columns.
- constraints for columns https://specs.frictionlessdata.io/table-schema/#constraints
I suspect you'll be adding `name` etc to the schema soon so haven't done anything for those. We can discuss adding constraints later. I'l go ahead and delete the `datatable-schema` branch and PR now.
> Add a SpreadsheetSchema.md

- index.es.js
- src/contexts/JsContext.js
- src/function/FunctionDocument.js
- src/function/FunctionDocumentImporter.js
- src/function/FunctionSchema.rng
- src/function/importFunctionDocument.js
- src/function/index.js
- src/types.js
- tests/function/fixtures/code_include_1_any.js
- tests/function/fixtures/code_include_1_integer.js
- tests/function/fixtures/code_include_1_string.js
- tests/function/fixtures/defaults_1.fun.xml
- tests/function/fixtures/defaults_2.fun.xml
- tests/function/fixtures/maxi.fun.xml
- tests/function/fixtures/min.fun.xml
- tests/function/fixtures/min_plus_tests.fun.xml
- tests/function/fixtures/overloads_1.fun.xml
- tests/function/fixtures/overloads_2.fun.xml
- tests/function/functions.test.js
Some improvement to `Functions` and relevant parts of `JsContext`...
- remove `option.pack` from `JsContext` methods as it is an optimisation that we identified in July as causing confusion.
- fixes and improvements for multi-language dispatch of calls
- Add descriptive elements to the schema based on [our initial work on defining functions](https://github.com/stencila/stencila/issues/310#issuecomment-326141685) which was in turn informed by things like [JsDoc](http://usejsdoc.org/) and [R function documentation](https://cran.r-project.org/doc/manuals/R-exts.html#Rd-format);
- `<summary>` : short one sentence summary suitable for use in tooltips etc (like JsDoc `@summary`)
- `<relateds>` : names of related functions (like JsDoc `@see`)
- `<examples>` : examples of usage (like JsDoc …
> WIP: Updates to Functions

- src/types.js
- tests/types.test.js
Fixes an issue when calling a function in mini when the param type had no decendant types array.
> Ensure an array for each type

- src/sheet/SheetLinter.js
- src/value.js
- tests/value.test.js
Fix for #480. Currently the type system treats `integer` as a specialisation of `number` and there is no `float` type. This remove generation of the `float` type in various places.
> Remove generation of a float type

- src/contexts/Context.js
- tests/contexts/Context.test.js
Bug in transpilation regex which caused ranges with a `0` in them,  like `A1:A10` to be mishandled.  Adds unit tests.
@oliver---- : could you please review and merge.
> Fixes bug in transpilation regex

- src/contexts/ContextHttpClient.js
- src/contexts/MiniContext.js
- src/host/Host.js
- tests/contexts/MiniContext.test.js
- tests/contexts/libtest.js
At present only Javascript function libraries can be loaded and only at build (bundling) time. This PR allows for dynamic loading of libraries from external execution contexts (e.g. R, Python) in alternative languages.
The use case for this functionality is a researcher who would like to wrap existing R or Python code and make it available as a Stencila function. We are trying to keep this process as simple as possible and allow users to use existing documentation formats and tools. Allowing for "hot-loading" functions provides some motivation - allowing them to see their function immediately available - and for manual testing.
For example, here is an RStudio session which uses the [stencila/r](https://github.com/stencila/r) package to register some custom functions with Stencila:
- …
> Dynamically loading of functions

- .travis.yml
- Makefile
Changing the name of`build` to `dist` (which is more standard naming) broke the deployments of PR builds to builds.stenci.la.
Just changed the name of the folder that is deployed and make some other fixes related to the name change.
> Fix build deployments

- examples/index.html
Charset is broken on builds.stenci.la
Found out this can be fixed by explicitly providing the charset in the HTML, so did just that.
> Add charset="utf-8" instruction to example HTML.

- src/project/Project.js
Some keyboard shortcuts were not working when no editor has a focus (e.g. CMD+F for bringing up a find and replace dialog).
Solved this by connecting the global key handlers on Project / app level.
> Connect global key handlers on app level

- docs/_sidebar.md
Just a bit of cleanup in the sidebar docs navigation
> Renamed Environment -> Images and removed link in computation menu

- src/sheet/SheetComponent.js
- src/sheet/SheetEditor.js
Current type over relies on experimental technology which is working only in chrome bigger than 60 and opera. 
This PR changes implementation to more classical one.
> Cross browser type over.

- app/app.js
- src/StencilaArchive.js
- src/article/index.js
- src/engine/Engine.js
- src/host/Host.js
- src/project/Project.js
- src/sheet/SheetLoader.js
- src/util/setupStencilaContext.js
- tests/engine/Engine.test.js
Currently there is some confusion about application context. E.g. EditorSessions do define their own 'context', but not use the context provided by the application.
This change tries to tidy up the mess a bit, reducing some of the confusion.
> Improve application setup

- src/article/CellComponent.js
After the last refactor, cell values are sometimes rendered even if the variable was assigned.
The cell component shows the retained value only if the variable is not assigned.
> Fix regression in cell value rendering.

- src/article/ArticleAdapter.js
- src/article/ArticleEditorCommands.js
- src/article/ArticleEditorPackage.js
- src/article/CellComponent.js
- src/article/_cell.css
- src/engine/Cell.js
- src/engine/CellErrors.js
- src/engine/CellGraph.js
- src/engine/Engine.js
- src/shared/AutoRunCommand.js
- src/shared/RunAllCommand.js
- tests/engine/Engine.test.js
The original idea was to introduce breakpoints to give the user more control of cell execution e.g. in presence of long-running tasks.
For sake of simplicity, we introduce a flag on document level, that controls whether cells are evaluated automatically or triggered by the user explicitly.
A manual request for evaluating a cell is interpreted as 'run this cell and all its dependencies' (i.e. anything needed to run this cell).
> Manual vs automatic evaluation of cells

- package.json
- src/engine/Engine.js
- src/shared/cellHelpers.js
- src/shared/expressionHelpers.js
- src/sheet/SheetAdapter.js
- src/sheet/SheetCell.js
- src/sheet/SheetCommands.js
- src/sheet/SheetDocument.js
- tests/contexts/libtest.js
- tests/engine/Engine.test.js
- tests/sheet/transformCellRangeExpression.test.js
Cell range expressions in sheets have not been updated when changing the sheets structure, via insert/remove rows/columns.
- introduced Engine API react on updated structure
- creating transformations for expressions that contain cell references or ranges
- making it work with undo/redo
- transclusions are not supported yet
> Cell range updates (first round)

- docs/languages/js/README.md
Why: I think the example was missing here (it's the code block directly after a sentence introducing something new).
What: I added the `pars` example to the code.
> Add example for `pars` property

- package.json
- src/engine/Sheet.js
- src/sheet/SheetClipboard.js
- src/sheet/SheetDocument.js
- src/sheet/sheetManipulations.js
- tests/engine/Engine.test.js
- tests/sheet/Sheet.test.js
- tests/sheet/SheetClipboard.test.js
At the moment, when pasting a table into a sheet that is larger than the sheet itself, the data gets truncated. See https://github.com/stencila/desktop/issues/35
This PR introduces logic that automatically adds columns and rows as necessary to fit the pasted data.
> Resize sheet on paste

- src/shared/FunctionUsageCommand.js
Why: We want to make a function helper tooltip less obtrusive.
What: Number of alternative strategies when to show a tooltip were suggested here #641.
The first take is to show it only when a cursor is on the function name.
> Only show the tooltip when cursor is on the function name.

- src/article/CellComponent.js
- src/contexts/JsContext.js
- src/engine/CellGraph.js
- src/engine/Engine.js
- src/shared/cellHelpers.js
- src/sheet/SheetCellComponent.js
- tests/engine/CellGraph.test.js
- tests/engine/Engine.test.js
- tests/index.html
- tests/shared/cellHelpers.test.js
Currently some cell errors are not very revealing. E.g.
- 'Unresolved inputs.' when one or more inputs could not be resolved
- 'Cyclic Dependency' when there is a cyclic dependency
Being there already in the error instances, this PR introduces a cell error message helper that exposes this information.
- Additionally I have fixed some bugs in the Engine related to cell updates.
- And added tests for `cellHelpers`.
On the long run we would like to have even more, such as being able to jump to the source of errors.
> Better message for some errors and Engine fixes

- src/article/CellComponent.js
Why: as were reported in #665 errors messages are gone after focusing other node. There were also considerations that rerender hides the error too eagerly.
What: this PR blocks cell rerendering in case of focus changing. It is also increasing error delay. So now it will show error only if you will not change the cell contents during one second (it was half a second before).
> Cell errors

- src/shared/CodeEditor.js
- src/shared/analyseCode.js
- src/shared/expressionHelpers.js
- src/sheet/SheetEditor.js
At the moment, in the Sheet editor, cell ranges of transcluded sheets are rendered like they were local references.
This PR makes use of the existing symbol parsing, used by the engine, to extract better information about cell and range references.
It also fixes an old bug due to wrong registration, which results the cell range renderer being called too early.
Fixes #663
> Fix cell range transclusion issue

- src/sheet/FormulaEditor.js
- src/sheet/SheetEditor.js
This behavior is common Spreadsheet UX, and currently missing.
See: #364 
This PR handles the TAB event received from the FormulaEditor and moved the selection to the next column.
Fixes #364
> TAB confirms cell editing and moves to next column.

- package.json
- src/shared/SwitchTypeDropdown.js
see #677
What?
While there might be another root of the problem these changes make the implementation more robust. 
See also https://github.com/substance/substance/pull/1184
> Fix issue 677

- src/shared/cellHelpers.js
Syntax errors in mini are overly complex.
This PR turns them into a simple 'Syntax Error', which is apparently less revealing, but also less obtrusive.
> Simplify mini syntax error messages.

- package.json
- src/article/ArticleEditorPackage.js
- src/article/CellComponent.js
- src/host/Host.js
- src/shared/analyseCode.js
- src/sheet/SheetPackage.js
So we can try using `JupyterContexts` in https://github.com/minrk/jupyter-dar ! See the related PR 
https://github.com/stencila/node/pull/42
> Integrate with JupyterContext

- src/shared/analyseCode.js
We have seen some errors in the tokeniser used for syntax-highlighting. See https://github.com/stencila/desktop/issues/54 ( item 3. )
This PR adds a guard  that checks that the tokenizer is actually available for a given language, before calling into Prism, and then fails gracefully by skipping the tokenization and displaying an error message on the console.
While the source of the error seems to be a wrong language identifier, which we need to investigate further, this still makes sense for sake of robustness.
> Avoid invalid calls into Prism

- src/StencilaWebApp.js
- src/article/ArticleLoader.js
- src/article/loadPersistedCellStates.js
- src/project/Project.js
- load cell states from persisted code cells
- disable starting the engine after loading the document
- show a confirm dialog and start engine when the user toggles 'Reproducible' the first time
> Persisted state

- src/StencilaArchive.js
- src/article/ArticleExporter.js
- src/article/persistCellStates.js
- src/shared/_connectDocumentToEngine.js
- src/shared/_initStencilaArchive.js
- src/stencilaAppHelpers.js
For the RDS prototype we need to be able to render cells 'statically' without running the engine.
For that we need to store a little more data from the cell state.
For the moment, this is only the output name of a cell. The output value itself is already persisted.
> Persist some cell state

- node/src/types.ts
- rust/src/config.rs
- rust/src/errors.rs
- rust/src/lib.rs
- rust/src/telemetry.rs
This adds a `telemetry` module. Initially all this does is define some configuration settings for CLI and Desktop  (analogous to those in `logging`). In the future we may add functionality and configuration for reporting other metric e.g. from Stencila workers inside Docker containers.
> feat(Telemetry): Add telemetry module

- Cargo.lock
- cli/main.rs
- rust/Cargo.toml
- rust/src/binaries.rs
- rust/src/config.rs
- rust/src/lib.rs
- rust/src/plugins.rs
- rust/src/utils/fs.rs
- rust/src/utils/tests.rs
Adds the `binaries` module for locating, running and installing third party binaries.
Binaries may be used as runtimes for plugins (e.g. Node.js, Python) or
are used directly by the `methods` module (e.g Pandoc).
This modules defines the `Binary` `struct` that can be used to define a
binary (e.g. how to determine the current version, how to download
a desired version) and functions for resolving, installing and executing
those binaries.
> Binaries module

- desktop/src/main/config/index.ts
- desktop/src/main/config/window.ts
- desktop/src/main/document/index.ts
- desktop/src/main/global/index.ts
- desktop/src/main/index.ts
- desktop/src/main/launcher/index.ts
- desktop/src/main/launcher/window.ts
- desktop/src/main/onboarding/index.ts
- desktop/src/main/onboarding/window.ts
- desktop/src/main/project/index.ts
- desktop/src/main/project/window.ts
- desktop/src/main/store/index.ts
- desktop/src/main/utils/handler.ts
- desktop/src/preload/errors.ts
- desktop/src/renderer/components/app-document/app-document-editor/app-document-editor.tsx
- desktop/src/renderer/utils/errors/index.ts
This PR contains several fixes for the desktop client.
Previously IPC handlers registered and removed upon creation/destruction of a window.
However since these handlers are shared between windows, and the fact that a user can open up multiple windows of the same type meant that we were incorrectly removing handlers which were still necessary.
To address this we now have a `makeHandlers` function which accepts a window ID and then tracks if the handlers are required by any windows or not.
The additional benefit of this approach is that I was able to remove try/catch wrapper when registering the handlers.
---
Another bug fixed was the editor state being lost when navigating between an image preview and a text document.
This was due to a race condition where the reference to the editor …
> Desktop errors and handlers

- node/src/types.ts
- rust/src/documents.rs
Bug #1118 was caused when serializing a document that had `Resource` other than a `Node` i.e. a code `File` that was the resource itself. This now serializes the `relations` property as a vector of subject-relation-object triples.
```sh
cargo run --manifest-path cli/Cargo.toml -- documents show fixtures/projects/daggy/article.json --display json
```
```json
{
"id": "do-RDwWsyGOQAFhRvML1anD",
"path": "/home/nokome/stencila/repos/stencila/fixtures/projects/daggy/article.json",
"project": "/home/nokome/stencila/repos/stencila/fixtures/projects/daggy",
"temporary": false,
"status": "synced",
"name": "article.json",
"format": {
"known": true,
"name": "json",
"binary": false,
"preview": true,
"extensions": []
},
"previewable": true,
"relations": [
[
{
"type": "Node",
"path": …
```
> fix(Documents): Make serialization of relations more robust and less lossy

- Cargo.lock
- node/src/documents.rs
- rust/codec-html/src/encode.rs
- rust/codec-html/src/encode/inlines.rs
- rust/stencila/Cargo.toml
- rust/stencila/src/documents.rs
- rust/stencila/src/patches/inlines.rs
- rust/stencila/src/patches/mod.rs
- rust/stencila/src/patches/structs.rs
This PR aims to fix any issues with rendering / patching (based on on-disk changes) HTML previews of Jupyter Notebooks (`.ipynb`).
Issues confirmed so far:
- patching of `Object` and `Array` code chunk outputs is not supported (this requires changes to the generation of the Rust types for these which in turn is waiting on merging the `schema` repo into this one).
> Fix: Jupyter Notebook / HTML patches

- Cargo.lock
- rust/codec-html/Cargo.toml
- rust/codec-html/src/encode.rs
- rust/codec-html/src/encode/others.rs
- rust/stencila/src/patches/mod.rs
- rust/stencila/src/patches/others.rs
- rust/stencila/src/patches/structs.rs
- rust/stencila/src/patches/works.rs
- web/src/patches/checks.ts
- web/src/patches/dom/add.ts
- web/src/patches/dom/move.ts
- web/src/patches/dom/remove.ts
- web/src/patches/dom/replace.ts
- web/src/patches/dom/resolve.ts
- web/src/patches/dom/transform.ts
This enables patches for properties of `Article` (and other creative work node types) such as `authors`, `datePublished`, and `references`.
In the process it makes some improvements in the `web` module to avoid panics when addresses can not be resolved (e.g. when a property is not yet encoded to HTML e.g `datePublished` currently is not).
@alex-ketch I went ahead and did because I thought it would be less work than it ended up being (of course!) and I thought it would avoid confusion in the future ("why is the title not updating"). I also points towards some additional work that needs to be done for patches in general (which I will set up an issue for).
Will merge; mainly FYI.
> Enable patching of article (and other creative works) properties

- desktop/src/main/project/index.ts
- desktop/src/renderer/client.ts
- desktop/src/renderer/components/app-document/app-document-preview/app-document-preview.tsx
- desktop/src/renderer/store/project/entities.ts
- desktop/src/renderer/store/project/projectSelectors.ts
- From the list of available themes I've dropped F1000, Nature, and PLoS themes until we've had time to review and refine them.
- Changing the preview theme now persists the setting to the project.json file
Close #1248
> Desktop: Reduce number of themes, save changes to project settings

- rust/codecs/src/lib.rs
Whilst perusing the `codecs` crate I noticed some documentation was missing. This add that and cleans up some of the docs, including those that appear in the command line help.
> docs(Codecs): Add and clean up documentation

- node/src/dispatch.ts
- node/src/errors.rs
- node/src/lib.rs
- rust/stencila/src/errors.rs
The original intent here was to be able to associate non-fatal errors with user
actions in the desktop. But the use of the `attempt` function in Rust caused
confusion with  error propogation, particularly when using the CLI.
Furthermore, we alreading us`tracing:warn` and `tracing::error` for reporting
non-fatal errors so there was duplication and a lack of consistency on what
errors should go where.
> chore(Errors): Remove deprecated "sideband" error functions

- web/src/client.ts
Close #1198
This PR deviates slightly from the plan outlined in the original issue.
> {
reconnect_interval: 1000 + 4000 * Math.random() # 1-5 seconds
max_reconnects: 0 # unlimited
}
I've adjusted the parameters so that reconnection attempts continue for around 5 to 15 minutes.
Intent here being that if a server is going to respond, it should hopefully do so within this time period. If it doesn't, then there's likely a bigger issue at hand, and we avoid an endless runaway process if a client is left open in a background tab or some similar scenario. This should also hopefully reduce the impact of the "thundering herd" mentioned in the issue description"
If you'd like @nokome, I can also engage the underlying `rpc-websockets` library maintainers to gauge their willingness to accept a PR to …
> feat(Web): Attempt to reconnect to server

- rust/codec-html/src/encode/blocks.rs
- rust/codec-html/src/encode/others.rs
- rust/codec-html/src/snapshots/encode_nodes@code-chunk.json.snap
- rust/node-execute/src/compile.rs
- themes/src/themes/wilmore/styles.css
- web/src/index.ts
Makes several changes to HTML encoding of the `code_dependencies` and `code_dependents` properties of `CodeChunk`s, and the `code_dependencies` property of `CodeExpression`s (they have no dependents):
- Use `<stencila-code-dependencies>` and `<stencila-code-dependency>` custom elements for both properties but keep as separate lists distinguishable by `slot` attribute
- Use `node-kind` instead of `node-type` to avoid conflict with native DOM attribute name
- Add `label` property and use for `CodeChunk.label` and `Parameter.name` e.g.
```html
<stencila-code-dependency node-kind="Parameter" node-id="pa-1" label="c" execute-auto="Needed">
</stencila-code-dependency>
```
> fix(HTML encoding): Refinement to encoding of code dependencies

- rust/images/src/change_set.rs
- rust/images/src/snapshot.rs
1. If there is no sorting, multiple computations will have different digest when there are multiple changes between snapshots 
2. This should be _other_, otherwise it won't find the file that is _Change::Added_ when it write to layer
> solve bug:same transformation, the calculated digest is different

- rust/images/src/change_set.rs
If change_set includes a new folder, the generated sha256 digest will be different, even though the folder name is the same(but the origin super path is different).It's kind of hard to describe the problem, how do I describe it to make it clear?
> Avoid inconsistent digest caused by folders

- README.md
This PR adds one line to `README.md` cli install instructions: Users need to `cd` into the recently extracted directory before moving the binary to `/usr/local/bin`.
> chore(docs): review of manual cli install instructions for linux

- package-lock.json
- web/package.json
- web/src/views/source.ts
**details**
add the search key mappings from @codemirror/search to enable the crtl-F
have set the search interface controls to appear at the top.
currently using default options for keyMappings and search config,
The codemirror search options will only open if the editor is in focus, otherwise it will default the browser search. if we want to set this that is always focuses on the I suggest creating this in another issues.
The key mappings and the further config options can be found here: https://codemirror.net/docs/ref/#search
**related issues**: closes#1807
> feat(views/source): add in doc search key mappings

- package-lock.json
- web/package.json
Digging into this @nokome, the issue is how paged.js splits up selectors:
```js
...
selector.split(",")
...
```
This doesn't work well with more modern css selectors like `:where` or `:has` or `:is`:
```css
[data-root] :where(p):not(:where([class~="not-prose"], [class~="not-prose"] *)) {
...
}
```
It seems to be a known issue & the solution is to roll back to the previous patch:
https://github.com/pagedjs/pagedjs/issues/166#issuecomment-1854701340
I can confirm that this works.
---
Looking at the release notes for `0.5.10` there are some minor updates that are worth looking at patching in our code as well (PR 301 introduces the issue that affects us).
https://github.com/tailwindlabs/tailwindcss-typography/releases/tag/v0.5.10
@nokome I've rolled back the version. I think when we get round …
> fix(package.json): rolled back to tailwind/typography@0.5.9

- web/src/clients/client.ts
- web/src/clients/codemirror.ts
- web/src/clients/format.ts
- web/src/clients/nodes.ts
- web/src/clients/object.ts
- web/src/clients/prosemirror.ts
- web/src/views/dynamic.ts
**details**
re implement the ws connection logic in the abstract `Client` class
This implements events (based on the code in issue #1785) when connecting, reconnecting and disconnecting
Have added another optional parameter to the constructor called `clientType` to allow instances to pass a string to be used in the body class / event name
**related issues**:  #1785
> feat(client): implement websocket connection logic

- rust/assistant/src/lib.rs
- rust/assistants/src/lib.rs
This partially fixes #1916.
We still need to merge the instructions and the original text for a markdown.
> Fix #1916 modify blocks

- Cargo.lock
- assistants/builtin/edit-blocks.md
- assistants/builtin/edit-code-chunk.md
- assistants/builtin/edit-inlines.md
- assistants/builtin/insert-block-image.md
- assistants/builtin/insert-code-chunk.md
- assistants/builtin/insert-code-expression.md
- assistants/builtin/insert-code-figure.md
- assistants/builtin/insert-empty-table.md
- assistants/builtin/insert-figure-caption.md
- assistants/builtin/insert-filled-table.md
- assistants/builtin/insert-image-figure.md
- assistants/builtin/insert-inline-image.md
- assistants/builtin/insert-math-block.md
- assistants/builtin/insert-math-inline.md
- assistants/builtin/insert-ordered-list.md
- assistants/builtin/insert-unordered-list.md
- rust/assistant-specialized/src/lib.rs
- rust/assistant/Cargo.toml
- rust/assistants/Cargo.toml
- rust/assistants/src/lib.rs
- rust/assistants/tests/assistants.yaml
- rust/assistants/tests/specialized.rs
This shifts the specialised assistants to using examples with embeddings rather than regexes for matching.
> DRAFT: feat(assistants): use embeddings

- web/src/apps/main.ts
- web/src/images/lineWrap.svg
- web/src/twind.ts
- web/src/views/source/panels.ts
**details**
apply some styling to the bottom panel of the source editor, including toggle and active state for the word wrap button.
design:
implementation:
related issues: closes #1958
> feat(bottom-panel): style bottom panel controls

- Cargo.lock
- rust/assistant-specialized/src/lib.rs
- rust/assistant/Cargo.toml
- rust/assistant/src/lib.rs
- rust/assistants/tests/specialized.rs
This isolates the embeddings, putting all the construction and comparison code and related data into one structure.
Some notes:
- The texts are now stored along the embeddings, making a copy. But I think this will make tuning / tracing etc far easier.
- I now calculate the instruction_text on construction of the Task, rather than doing it lazily (we need it all the time anyway).
- The full matrix comparison of instruction examples in now in the specialized.rs test (under assistants)
> refactor(assistants): pull out embeddings

- Cargo.lock
- rust/assistant-anthropic/src/lib.rs
- rust/assistant-google/src/lib.rs
- rust/assistant-mistral/src/lib.rs
- rust/assistant-openai/src/lib.rs
- rust/assistant/Cargo.toml
- rust/assistant/src/lib.rs
- rust/cli-utils/Cargo.toml
- rust/cli-utils/src/lib.rs
- rust/cli-utils/src/table.rs
- rust/cli/Cargo.toml
- rust/cli/src/cli.rs
- rust/secrets/Cargo.toml
- rust/secrets/src/cli.rs
- rust/secrets/src/lib.rs
- rust/secrets/src/main.rs
- rust/server/Cargo.toml
- rust/server/src/server.rs
Closes #1909
Still to do:
~~- [ ] Add `SecretsClient` in `web` to use REST API exposed by server~~
> feat(secrets): add support for secrets management

- web/src/views/dynamic.ts
- web/src/views/source.ts
- web/src/views/static.ts
- web/src/views/visual.ts
**details**
This fixes an issue related to the document tabs in all views,
- when closing tabs sometimes the tabs are not associated with the panels properly
The issue was not with the logic, the view in the panels were not updating itself
TL:DR; 
Here's what was happening: 
If i had two tabs open with ids: doc_1 and doc_2.
and I closed doc_1 and the main LitELement updates,  doc_2 is now the only tab, however it has moved into the panel where doc_1 was before. The property `doc` was updated correctly and passed down to child elements, however the view (eg, source, visual) element inside that panel had no way of responding an update in the `doc` property. I have set it now so It reset each view in this case.
**related issue**: #2065
> fix(views): set views to respond to doc property update

- web/src/nodes/array.ts
- web/src/nodes/boolean.ts
- web/src/nodes/code-block.ts
- web/src/nodes/code-chunk.ts
- web/src/nodes/code-expression.ts
- web/src/nodes/code-inline.ts
- web/src/nodes/integer.ts
- web/src/nodes/math-block.ts
- web/src/nodes/math-inline.ts
- web/src/nodes/number.ts
- web/src/nodes/object.ts
- web/src/nodes/paragraph.ts
- web/src/nodes/string.ts
- web/src/nodes/styled-block.ts
- web/src/nodes/styled-inline.ts
- web/src/nodes/styled.ts
- web/src/ui/nodes/in-flow/block.ts
- web/src/ui/nodes/mixins/uiBaseClass.ts
- web/src/ui/nodes/on-demand/block.ts
- web/src/ui/nodes/on-demand/in-line.ts
- web/src/ui/split-drag/index.ts
- web/src/views/source.ts
- web/src/views/split.ts
**Description**
Previously we had a `node-card` component which allowed us to render a node in either `on-demand` or `auto` modes. `on-demand` was for allowing blocks to be rendered as users interacted with them, `auto` - the element rendered on the screen as is.
This did not take `inline` vs `block` elements into account.
This PR provides some new components:
- `stencila-ui-block-in-flow`: `ui/in-flow/block.ts`
- `stencila-ui-block-on-demand`: `ui/on-demand/block.ts`
- `stencila-ui-inline-on-demand`: `ui/on-demand/in-line.ts`
These have been applied to the following (plus some other minor node types):
- `CodeChunk`
- `CodeExpression`
- `CodeBlock`
- `CodeInline`
- `MathBlock`
- `MathInline`
- `StyledBlock`
- `StyledInline`
_Note:_ Some rendering issues have fallen out of this issue. See …
> Inline/block on demand & in flow

- rust/server/src/documents.rs
- web/package.json
- web/src/apps/main.css
- web/src/apps/main.ts
- web/src/shoelace.css
- web/src/shoelace.ts
- web/src/themes/default.css
- web/src/ui/nodes/card.ts
- web/src/ui/nodes/properties/author/index.ts
- web/src/ui/nodes/properties/execution-details.ts
- web/src/ui/nodes/properties/generic/collapsible.ts
- web/src/ui/nodes/properties/instruction-messages.ts
- web/src/views/dynamic.ts
Serve a document view (e.g. `?view=dynamic`; default is `static`) rather than app. The `apps/main.ts` is still there but likely to be removed.
@simonwinter & @mike-parkin you might want to review the commits to follow the approach taken here.
> refactor(web): single view pages

- web/src/ui/nodes/properties/authorship/authorship.ts
- web/src/ui/nodes/properties/code/code.ts
- web/src/ui/nodes/properties/code/utils.ts
**details**
fixes the white-space issue with the `<stencila-authorship>` component,
the issue was with whitespace and new lines in the html`` templates, (probably due to the 'inline' nature of the host element) these new lines and any leading / trailing whitespaces within the elements were being compressed into a single whitespace. even if removing all these from the the template, the sl-tooltip element was still adding the white space, this is because in the template of that element in the shoelace library contains the whitespace.
I have removed the sl toolitp and replaced it with a simple custom tip that is absolutely positioned, and appears on group hover.
I have formatted the html template in a way that adds no whitespace between elements, and added a `// prettier-ignore` instruction …
> Fix/whitespace in authorship highlight #2223

- web/src/ui/nodes/properties/code/utils.ts
- web/src/ui/preview-menu/index.ts
**details**
Use 'Inter' as the font for error messages, will default to a mono if this is not available
(also patch the z-index of the preview burger menu)
**related issue** #2229
> fix: execution message font

- web/src/ui/nodes/properties/author/index.ts
- web/src/ui/nodes/properties/execution-details.ts
- web/src/ui/nodes/properties/provenance/provenance.ts
**details**
Make the following changes:
And also fixes the authors property layout on smaller screens.
*related issue*: #2209
> Fix/instruction block UI

- web/src/ui/nodes/mixins/toggle-chip.ts
- web/src/ui/nodes/node-card/on-demand/block.ts
- web/src/ui/nodes/node-card/on-demand/in-line.ts
**details**
changes some simple positional and behavioural properties of the node card toggle chip
- Node chips remain visible when the card is expanded. and clicking again will collapse.
- chip icon is swapped to chevron when card is open.
- node chips are now positioned relative to the 'stencila-ui-collapsible-animation' component, instead of the content container, this keeps them inline with the top corner of the NodeCard. and also helps spread out the card chips.
- inline chips have be re-positioned, to avoid overlapping the inline card when it opens.
**related issue**:  #2236
> refactor: node chip behaviour

- examples/nodes/article-ark/article-ark.dom.html
- examples/nodes/article-labels/article-labels.dom.html
- examples/nodes/code-chunk/code-chunk.dom.html
- examples/nodes/figure/figure.dom.html
- examples/nodes/table/table.dom.html
- json/CodeChunk.schema.json
- json/Figure.schema.json
- json/Table.schema.json
- rust/schema/src/implem/code_chunk.rs
- rust/schema/src/implem/figure.rs
- rust/schema/src/implem/mod.rs
- rust/schema/src/implem/table.rs
- rust/schema/src/implem/utils.rs
- rust/schema/src/types/code_chunk.rs
- rust/schema/src/types/figure.rs
- rust/schema/src/types/table.rs
- schema/CodeChunk.yaml
- schema/Figure.yaml
- schema/Table.yaml
- web/src/nodes/code-chunk.ts
- web/src/nodes/table.ts
- web/src/themes/default.css
This add a `<span class="figure-label">` or a `<span class="table-label">` to the first paragraph of the `caption` (if any) of `Figure`, `Table` and `CodeChunk` nodes. This is done because doing this via CSS and/or CSS was proving difficult.
There are some other changes which make the generated HTML more semantically correct:
- for `Figure`, nest `<figcaption>` within `<figure>`
- for `Table`, nest `<caption>` within `<table>`
- for `CodeChunk`,  put the caption before the `outputs` if the label type is a table, and after if it is a figure
See the diffs for the HTML snapshots.
> refactor(dom html): add label to captions of `Table`, `Figure`, and `CodeChunk`

- web/src/ui/nodes/icons-and-colours.ts
- web/src/ui/nodes/properties/authorship/authorship.ts
- web/src/ui/nodes/properties/code/utils.ts
**details**
Have swapped the provenance highlight out for opacity of text
-> has the 6 (0->5) mi levels from `1 -> 0.5` opacity
in the content <stencila-authorship> component, the opacity is set on the text only (via the `--tw-text-opacity` alpha variable)
for the provenance in the code view, I can only set the elements opacity, this is not ideal, but does have a side effect of varying opacity when the text is selected see image below.
As the text in the codemirror is colored by the language extensions, it would be virtualy impossible to apply the opacity to the text only (until css acutaly creates a `text-opacity` property)
> Feat: use text opacity to display provenance

- vscode/src/webviews.ts
- web/src/ui/nodes/mixins/toggle-chip.ts
- web/src/ui/nodes/node-card/on-demand/block.ts
- web/src/ui/nodes/node-card/on-demand/in-line.ts
- web/src/views/vscode.ts
**details**
In the vscode view, when the user clicks on the 'view' button above a node in the markdown it will scroll to the relevant node in the webview and open the card.
It uses the `webview.postMessage` method to send an event to the window, which can be picked up in the `vscode` component. 
in this case the message contains a `scrollTarget` property of the id for the node to scroll to.
**related issue**: #2251
> feat(vscode): send message events to webview

- vscode/src/webviews.ts
- web/src/clients/webview.ts
- web/src/views/vscode.ts
**details**
Created a new client class for the vscode webview (`WebViewClient`)
This client recieves and handles the 'message' events.
right now, in practice this is merely a refactoring of current functionality. as we only have one event type active, but this can be expanded upon.
For sending messages it has a static method `postMessage` which can be used to send commands to the panel vis the `vscode` api instance which has to be declared in the `panel.webview.html` string.
if you want to test this works add the line to a lifecycle hook of any element and you should see an error alert pop up in vscode.
```
WebViewClient.postMessage({ command: 'error', text: 'test' } )
```
> refactor(views/vscode.ts): create new webviewclient to handle events

- examples/kernels/if-block/standalone-polyglot.json
- examples/kernels/if-block/standalone-polyglot.md
- web/src/assets/icons/clause-elif.svg
- web/src/assets/icons/clause-else.svg
- web/src/assets/icons/clause-if.svg
- web/src/nodes/code-block.ts
- web/src/nodes/code-chunk.ts
- web/src/nodes/if-block-clause.ts
- web/src/nodes/if-block.ts
- web/src/ui/nodes/mixins/language.ts
- web/src/ui/nodes/node-card/on-demand/block.ts
- web/src/ui/nodes/properties/code/code.ts
Our designs for `IfBlock`s look like this:
My first iteration towards those designs are:
Note that we do not need the editing elements such as trash can, drag and drop grips, or language select right now.
@mike-parkin Could you take this over. There are several TODOs in `web/src/nodes/if-block.ts` and `web/src/nodes/if-block-clause.ts`.
Also, it would be good to fix this z-index issue if possible:
> fix(if block): improve web component

- web/src/assets/icons/array.svg
- web/src/nodes/array.ts
- web/src/nodes/boolean.ts
- web/src/nodes/integer.ts
- web/src/nodes/number.ts
- web/src/nodes/object.ts
- web/src/nodes/string.ts
**details**
Have swapped out the data type nodes form the block display to an inline, this allows them to be used in paragraphs etc without breaking the document flow.
> refactor: use inline for code output datatype nodes

- web/src/ui/nodes/node-card/on-demand/in-line.ts
- web/src/ui/nodes/properties/code/code.ts
**details**
fixes the code snippet z-indexing problem when the linting tooltip crosses into another code snippet Re. the if block clauses
> fix(code): z-indexing

- web/src/nodes/code-chunk.ts
- web/src/nodes/code-executable.ts
- web/src/ui/nodes/properties/code/code.ts
**details**
Removes regression of code snippet provenance highlights,
caused by prop drilling an array type that should have been a string.
> fix(code.ts): keep authroship attribute as string whilst being drilled

- web/src/nodes/article.ts
- web/src/nodes/provenance-count.ts
- web/src/ui/nodes/icons-and-colours.ts
- web/src/ui/nodes/properties/authors-provenance.ts
**details**
Have applied some simple formatting style rules and labeling to the article level authors provenance slotted elements.
These should be similar to the node card displays of the same elements.
Also removed deprecated code from the `UIAuthorsProvenance` class
related issues: closes #2339
> refactor: apply new styles to article author provenance

- vscode/package-lock.json
- web/src/nodes/image-object.ts
**details**
The prose typograhpy from the default theme was leaking into svg elements inside the image-object nodes, specifically mermaid.
I have set the rule `all: initial` on the svg element to override this, thus reseting the line height.
> fix(image-objects): reset all styles on svg el to avoid prose inherit

- vscode/src/authentication.ts
https://github.com/stencila/stencila/issues/2336
Ideally we would show the users name when logged in, but usually they have not entered it and it falls back to userId. This PR will try to find an email address to fall back to before resorting to userId.
> fix(vscode): show account email if available, when account logged in

- .devcontainer/demo/Dockerfile
- .devcontainer/demo/devcontainer.json
Here is the demo container for inclusion in the main stencila repo.
You will need to enable this in codespaces on this repository manually in the repo's Codespaces Settings:
https://docs.github.com/en/codespaces/developing-in-a-codespace/creating-a-codespace-for-a-repository
It will prompt for a STENCILA_API_TOKEN when started up, you can add this environment variable to your account globally at: https://github.com/settings/codespaces
> feature(devcontainer) - a `.devcontainer` profile for demoing the vscode extension

- web/src/themes/default.css
**details**
- reduced font size from 1rem to 0.875rem.
- added darker bg colour.
- reduced the border radius.
- removed the backticks (these were coming from the '@tailwind/typography' plugin).
- added some light horizontal padding to provide some breathing room at the start and end of the block.
closes #2413
> fix(code-inline): remove backtick, reduce font size

- web/src/ui/nodes/properties/generic/timestamp.ts
- web/src/utilities/getModeParam.ts
**details**
when the window is in 'test-expand-all' mode, the timestamp components will replace the dynamic values with 'some-time-ago' to avoid flagging in the regression screenshot tests.
closes: #2448
> fix(timestamp): replace relative time with consistant value for test 2448

- rust/cli/src/compile.rs
- rust/cli/src/convert.rs
- rust/cli/src/execute.rs
- rust/cli/src/render.rs
- rust/codecs/src/cli.rs
- rust/codecs/tests/snapshots/specs__specs.snap
- rust/format/src/lib.rs
- rust/prompt/src/instruction/mod.rs
added Input and Output format rows to the table created by the `codecs` command and colors to the status 
also added a quick message in the convert help page
> List formats

- rust/server/src/documents.rs
- rust/server/src/server.rs
- rust/server/src/statics.rs
- web/src/ui/nodes/mixins/toggle-marker.ts
fixes a regression caused by moving over to the new card layout in the togglemarker mixin
We now use the puiblic `this.closeCard()` method for a close button click event, this method fires the necessary event to let parent entities know there has been a change.
related issues: #2485 #2486
> fix(web): add bubbling event to card close click

- web/README.md
- web/src/nodes/code-chunk.ts
- web/src/nodes/for-block.ts
- web/src/nodes/if-block.ts
- web/src/nodes/instruction-block.ts
Have refactored out the use of @query decorator in Entity sub class elements,
Have left one exception in the `InstructionBlock` element, where the suggestionSlot  query property is used thoughout the class methods when checking and updating visible suggestions. As it is not utilised ina lifecylce hook the
Have added a note to the web/README related to using the query decorator inside `Entity` classes.
> refactor(web): phase out lit query decorator

- docs/reference/cli.md
- rust/publish-ghost/Cargo.toml
- rust/publish-ghost/src/lib.rs
- rust/secrets/src/lib.rs
This PR enables users to publish Stencila docs to Ghost.
Features:
- Stores secrets within the OS keyring via Stencila's secrets,
Limitations: 
- Uses the text codec to create a rough version of the doc in Ghost. Intended to be updated with `codec-lexical` when it's available.
- Lack of testing (am unfamiliar with some of the mechanics)
- Only files are supported currently, rather than directories
> Publish to Ghost

- Cargo.lock
- rust/codec-lexical/src/blocks.rs
- rust/document/src/lib.rs
- rust/images/src/lib.rs
- rust/node-media/Cargo.toml
- rust/node-media/src/lib.rs
- rust/publish-ghost/Cargo.toml
- rust/publish-ghost/src/lib.rs
- rust/schema/src/implem/media_objects.rs
This adds a new crate `node-media` which factors out some functionality we had elsewhere for marshaling images in a document into an image directory with hash filenames.
It uses this crate to extract images from documents, upload them to Ghost, and rewrite the URLs of nodes in the document as needed.
@timClicks: I'll pass this over to you to finish off.
I've done some preliminary testing with this Markdown file
```md
A Base64 encoded image:
A file relative to this doc:
```
> Ghost publishing: image handling

- rust/publish-ghost/src/lib.rs
add `--id` flag for use when publishing generated files that would clobber the identifier
> feat(publish ghost): add id flag

- rust/codec-lexical/src/blocks.rs
- rust/codec-lexical/tests/snapshots/examples__ghost.koenig.snap
- rust/codec-lexical/tests/snapshots/examples__playground.lexical.snap
encode flat lists to lexical lists for easy of editing on ghost and encode nested lists to markdown because lexical does not support them.
> ghost nested lists encoding

- rust/model/src/lib.rs
- rust/models-stencila/src/lib.rs
- rust/models/src/cli.rs
- rust/models/src/lib.rs
- vscode/src/models.ts
- web/src/nodes/model-parameters.ts
- web/src/system.ts
- web/src/ui/icons/icon.ts
- web/src/ui/icons/icons-shoelace.sh
- web/src/ui/icons/lightning-charge-fill.svg
@jduckles had the excellent idea of exposing model scores for overall quality (not specific to a particular prompt), cost, and speed in the select menu for models.
This implements that (currently with random scores pending adding those to `GET htpps://api.stencila.cloud/v1/models`) and more:
- the list of models is now sorted, across providers, in Rust, according to (a) routers always first, (b) quality score if any, (c) provider+model name
- the scores are displayed in the `stencila models list` command as colour coded numbers (and also in JSON or YAML when using the `--as` option)
- improved how models names & versions are displayed in the model selection menu which makes it consistent with the models sidebar menu
- the scores are displayed in the model selection menu using star, dollar …
> feat(models): expose quality, cost, and speed scores

- web/src/themes/default.css
- web/src/themes/nodes.css
**details**
refactors the styles for stencila 'nodes' out of the default.css theme file, this allow the rules for the nodes to be used independently, without having to be wrapped in a view or [root] node.
> refactor(web): move all node-related styles into seperate file

- web/src/nodes/figure.ts
- web/src/themes/default.css
- web/src/themes/nodes.css
- web/src/ui/nodes/properties/author.ts
**details**
enforce the overflow ellipsis on the author node `<stencila-ui-node-author>` to stop details overflowing container
> fix(web): stop text overflow in author elements

- Cargo.lock
- json/CodeExpression.schema.json
- rust/codec-docx/src/lib.rs
- rust/codec-latex-trait/src/lib.rs
- rust/codec-latex/src/lib.rs
- rust/codec-noweb/Cargo.toml
- rust/codec-noweb/src/lib.rs
- rust/codec-noweb/tests/examples.rs
- rust/codec-noweb/tests/examples/chunk.nw
- rust/codec-noweb/tests/examples/sexpr.nw
- rust/codec-noweb/tests/snapshots/examples__chunk.decode.losses.snap
- rust/codec-noweb/tests/snapshots/examples__chunk.encode.losses.snap
- rust/codec-noweb/tests/snapshots/examples__chunk.json.snap
- rust/codec-noweb/tests/snapshots/examples__chunk.nw.snap
- rust/codec-noweb/tests/snapshots/examples__sexpr.decode.losses.snap
- rust/codec-noweb/tests/snapshots/examples__sexpr.encode.losses.snap
- rust/codec-noweb/tests/snapshots/examples__sexpr.json.snap
- rust/codec-noweb/tests/snapshots/examples__sexpr.nw.snap
- rust/codec-pandoc/src/blocks.rs
- rust/codec-pandoc/src/inlines.rs
- rust/codecs/Cargo.toml
- rust/codecs/src/lib.rs
- rust/format/src/lib.rs
- rust/schema/src/implem/code_chunk.rs
- rust/schema/src/implem/code_expression.rs
- rust/schema/src/types/code_expression.rs
- schema/CodeExpression.yaml
- Currently named `NwCodec` and adds `Format::Nw` but given that `Rnw` appears to be the only extant use of `noweb` syntax and to avoid having to add something to apss language from file format through to `CodeChunk`/`CodeExpression` will rename to `RnwCodec` etc.
- Likely to merge this, as is, soon and not do further development: will be superseded by new `stencila knit` command which is less lossy with respect to LaTeX elements that Pandoc does not support.
> feat(rnw codec): add a `RnwCodec` for handling `.rnw` files

- Cargo.lock
- rust/cli/Cargo.toml
- rust/cli/src/cli.rs
- rust/document/src/lib.rs
- rust/images/src/lib.rs
- rust/knit/Cargo.toml
- rust/knit/src/cli.rs
- rust/knit/src/knit.rs
- rust/knit/src/latex.rs
- rust/knit/src/lib.rs
- rust/lsp/src/text_document.rs
- A new `knit` command which is similar to Sweave or Knitr it its approach. It uses existing infrastructure for document execution, but which rather than using existing codec, "decodes" documents into `Article`s made up of only:
- `RawBlock` - to hold raw markup (e.g. LaTeX, Markdown)
- `CodeChunk` - to hold executable code
- `Section` - for "islands" of markup and/or executable code that are not intended to be edited (useful for things like complex tables, diagrams etc)
- To do:
- Anticipate adding `unknit` command (to merge in changes form docx) soon, but not part of this PR.
> feat(knit): add `stencila knit` command
