stencila/stencila

web/stencil/StencilWriter.js, web/stencil/model/Stencil.js, web/stencil/packages/table/InsertTableCommand.js, web/stencil/packages/table/InsertTableTool.js, web/stencil/packages/table/createTable.js, web/stencil/packages/writer/WriterTools.js
Initial implementation. Not tested.
Some of the things as noted in comments should go into substance core.
=> Initial iteration on adding tables.

tests/documents/blockquote/alt-multiline.md, tests/documents/blockquote/default.html, tests/documents/blockquote/default.md
Some minimal changes to match what remark produces and to match expected output (the id in the header, for instance).
=> changes to blockquote to match remark output

tests/documents/input/default.html, tests/documents/input/default.md, tests/documents/output/default.html, tests/documents/output/default.md
just a couple changes to match what's expected / happening in other places.
=> small consistency changes for input and output

package.json, src/document/CellEngine.js, src/document/_document-editor.css, src/document/nodes/cell/CellComponent.js, src/document/nodes/cell/CellMixin.js, src/document/nodes/cell/CellStatusBar.js, src/document/nodes/cell/CellValueComponent.js, src/document/nodes/cell/_cell-status-bar.css, src/document/nodes/cell/_cell.css, src/document/vega-lite/VegaLiteComponent.js, src/document/vega-lite/_vega-lite.css, tests/documents/cell/default.html
=> Improved handling of runtime errors.

examples/docs/kitchensink.js, make.js, package.json, src/document/CellEngine.js, src/document/DocumentEditor.js, src/document/nodes/cell/CellComponent.js, src/document/nodes/cell/CellMixin.js, src/document/nodes/cell/CellStatusBar.js, src/document/nodes/cell/CellValueComponent.js, src/document/nodes/cell/MiniLangEditor.js, src/document/vega-lite/VegaLiteComponent.js
=> Improving cell rendering

guides/documents-intro/index.html, guides/welcome/index.html, src/js-context/functions/index.js
@michael Could you merge this in and perhaps add and edit as you see fit - I've done about as much as I can today!
=> Add guides

examples/document/app.js, guides/02-stencila-manual/index.html, index.es.js, src/context/ContextHttpClient.js, src/document/CellEngine.js, src/document/DocumentHTMLImporter.js, src/document/DocumentModel.js, src/document/DocumentPage.js, src/document/nodes/cell/Cell.js, src/document/nodes/cell/CellComponent.js, src/document/nodes/cell/CellHTMLConverter.js, src/document/nodes/cell/CellPackage.js, src/document/nodes/cell/ImageValueComponent.js, src/document/nodes/cell/_cell.css, src/host/Host.js, src/value.js, tests/document/CellEngine.test.js, tests/testHelpers.js, tests/value.test.js
This is still a wok in progress, don't merge yet. See #283.
=> Provides for cells with execution in remote contexts

README.md, examples/document/app.js, make.js
Allows closer mimicking of Desktop deployment during development
=> Allows for more env vars in dev; adds STENCILA_DISCOVER

src/document/DocumentEditorPackage.js, src/document/EditExtLinkToolMonkeyPatched.js, src/shared/FunctionUsageComponent.js, src/shared/_function-usage.css, src/shared/_index.css
Hacked the EditLinkTool to start prototyping the FunctionUsageComponent. We need to connect this now with the Mini editor, by parsing and analysing the mini expression.
=> Initial version of FunctionUsageComponent

examples/publication/app.js, src/contexts/MiniContext.js, src/engine/DependencyGraph.js, src/engine/NewEngine.js, src/function/index.js, src/host/Host.js, src/publication/Publication.js, src/shared/CellValueComponent.js, tests/contexts/MiniContext.test.js, tests/host/Host.test.js
Improved error handling in MiniContext.
=> MiniContext, Host, and FunctionManager

package.json, src/contexts/MiniContext.js, src/engine/DependencyGraph.js, src/engine/NewEngine.js, src/shared/cellHelpers.js, src/types.js
=> Evaluating Cells

src/engine/CellState.js, src/engine/NewEngine.js
Introducing `CellState.status`:
- `PENDING`: inputs have not been computed yet
- `INPUT_READY`: inputs ready and cell will be evaluated ASAP
- `INPUT_ERROR`: some of the inputs have errored
- `RUNNING`: cell is being evaluated
- `ERROR`: evaluation failed
- `OK`: evaluation succeeded
=> Improved cell state.

docs/concepts/cell-editor.md, docs/concepts/issue-manager.md, docs/log.md
Initial descriptions and specifications for topics 'issue-manager' and 'cell-editor'.
=> Some planning.

package.json, src/shared/CodeEditor.js, src/sheet/SheetCell.js, src/sheet/SheetCommands.js, src/sheet/SheetComponent.js, src/sheet/SheetDocument.js, src/sheet/SheetEditor.js, src/sheet/SheetPackage.js, src/sheet/SheetView.js, src/sheet/_sheet.css
Greater tidy-up and  a number of improvements.
See #467
=> Sheet improvements

src/sheet/SheetDocument.js, src/sheet/SheetRowHeader.js, src/sheet/SheetView.js
Removed experimental and buggy implementation for showing row issues.
=> Fix regression.

src/sheet/SheetEditor.js
=> Cell referencing

docs/steps/0005-extensible-type-system.md, docs/steps/README.md
This is currently WIP but comments welcome.
=> StEP 0005 Extensible type system

package-lock.json, package.json, src/contexts/MiniContext.js, src/sheet/SheetLinter.js, src/types.js, src/value.js, tests/contexts/MiniContext.test.js, tests/value.test.js
Primarily to reinstate the `plot` and `table` functions
=> Upgrade libcore

src/sheet/CellRangesOverlay.js, src/sheet/SheetComponent.js, src/sheet/SheetEditor.js, src/sheet/_cell-ranges.css, src/sheet/_sheet.css
Improved implementation according to discussion in #497
=> Cell references

examples/data/publication/manifest.xml, examples/data/publication/manuscript.xml, package.json, src/article/ArticleEngineAdapter.js, src/contexts/MiniContext.js, src/engine/CellGraph.js, src/engine/Engine.js, src/sheet/SheetEngineAdapter.js, src/util/getFullyQualifiedNodeId.js, src/util/setupStencilaContext.js
Fixes implementation to consider cells from different resources.
=> Transclusion

docs/README.md, docs/index.html
Why: Please describe why you are suggesting the PR.
What: Elaborate what your changes do, and how they address the problem described.
=> Added banner with WiP info

src/host/HostsComponent.js, src/host/_host.css
Why: There are broken styles now in hosts panel.
What: Fix styling issues.
=> Hosts panel.

src/article/ArticleEditorPackage.js, src/article/InsertReproFigCommand.js
Why: There is no ability to insert reproducible figure. 
What: This PR adds command for inserting reproducible figure
=> Insert reproducible figure command.

examples/r-sheet/r-sheet-notes.md
Why: Please describe why you are suggesting the PR.
What: Elaborate what your changes do, and how they address the problem described.
=> Notes explaining using Spreadsheets with R

src/shared/_cell-value.css, src/sheet/CellOverflowComponent.js, src/sheet/SheetCell.js, src/sheet/SheetCommands.js, src/sheet/SheetDocument.js, src/sheet/SheetEditor.js, src/sheet/SheetPackage.js, src/sheet/_sheet.css, src/sheet/sheetHelpers.js
We decided to remove display modes feature for some time and implement it later.
This PR removes everything related to concept of modes leaving only original "minimal" mode.
=> Remove display modes.

src/sheet/SheetComponent.js, src/sheet/SheetEditor.js
This PR fixes bugs 1-3 from #541.
=> Cell ref fixes.

src/shared/FunctionHelpComponent.js, src/shared/HelpComponent.js, src/shared/_context-pane.css, src/shared/_function-help.css, src/shared/_index.css, src/sheet/_sheet.css
Style changes as suggested in #613.
=> Improve help panel.

examples/py-jupyter/manifest.xml, examples/py-jupyter/py-jupyter.ipynb.jats.xml
Manual update to new Dar/JATS formats.
=> Fix Jupyter notebook example

src/engine/Engine.js
=> Allow user to force re-execution of a cell

src/article/CellComponent.js, src/article/_cell.css
=> Display language used in a cell.

.travis.yml, app/example.html, make.js, package-lock.json, package.json, src/contexts/ContextHttpClient.js, src/contexts/JsContext.js, src/contexts/MiniContext.js, src/function/FunctionManager.js, src/host/Host.js, src/shared/FunctionHelpComponent.js, src/shared/FunctionUsageComponent.js, src/shared/FunctionUsageTool.js, src/shared/ObjectValueComponent.js, src/shared/_cell-value.css, src/shared/_code-editor.css, src/shared/_function-help.css, src/shared/analyseCode.js, src/stencilaAppHelpers.js, src/util/setupStencilaContext.js, tests/contexts/JsContext.test.js, tests/contexts/MiniContext.test.js, tests/contexts/libtest.js, tests/document/transclusion.test.js, tests/util/setupEngine.js, tests/util/setupSheetSession.js
This PR is needed because of updates to the definition of function libraries in JS and other languages including:
- changes to how functions are called (allowing for variadic and extensible keyword arguments)
- allowing functions to be defined dynamically in external execution contexts (e.g. Node.js Python, R) e.g. in `libdh`
- changes in function definitions away from XML towards native syntax for each language (e.g. JSDoc)
For more details see  https://github.com/stencila/libcore/pull/20 and https://github.com/stencila/node/pull/30
https://github.com/stencila/libcore/pull/20 needs to be completed, merged and published before merging this.
- mostly refactoring/renaming
- does add an undocumented 'hack' to allow functions to be defined within a cell - this is really useful for less …
=> Function libraries and call semantics

src/contexts/ContextHttpClient.js, src/shared/ValueComponent.js
Some minor fixes to deal with display and registration of functions returned from cells.
Allow for display of extended types (e.g. functions); unpack functions before registering
=> Function values

package.json, src/StencilaArchive.js, src/article/ArticleEditorPackage.js
Merge not before new Texture npm version is ready. Depends on https://github.com/substance/texture/pull/511 to be merged and published.
=> Upgrade texture

package-lock.json, package.json
Upgrading substance-bundler with all tooling in latest state.
=> Upgrade bundler

src/engine/CellGraph.js, src/engine/Engine.js, tests/engine/Engine.test.js
see #596 
This PR adds a test revealing the issue, and fixes the implementation.
Fixes #596
=> Clear errors when cell is constant

package.json, src/project/Project.js
=> Fix regressions

package-lock.json, package.json, src/cli.ts
Added stencila/logga to package.json then added a handler to send logga messages to winston.
=> feat: Added handler to log from logga to winston

demos/README.md, demos/demo-overview.md, demos/examples/README.md, demos/examples/output/.gitignore, package-lock.json
[Stencila 0.28.2 Demo](https://asciinema.org/a/MGhcJ4OYtxvNU2fJ5M4uhQgfX)
Signed-off-by: Jackie Wijaya <jackie.wijaya@gmail.com>
=> docs: Add demo video

help/hub/getting-started.md, help/intercom.ts, help/template.md, package-lock.json, package.json, src/commands/convert.ts, src/commands/process.ts, src/commands/serve.ts, src/commands/system.ts
This PR adds:
- Updates Encoda and Typescript dependencies
- a template for new help documents
- Adds "Further Reading" links automatically to articles
=> Intercom doc generation improvements

help/hub/getting-started.md, help/hub/organizations/manage-organization-settings.md, help/hub/organizations/manage-organization-users.md, help/hub/projects/create-a-project.md, help/hub/projects/manage-project-sources.md, help/intercom.ts
The CI build will now throw errors and terminate early in case of issues.
This helped me find a few broken relative links across the documentation files.
=> Add "Edit Docs" link to Intercom articles & misc fixes

README.md
=> copyedit in README.md

rust/src/config.rs
Pretty minor, but I guess that's a good place to start..
=> chore(clippy): Remove unnecessary return

.ci/azure-pipelines.yml, .ci/prepare-release.sh, desktop/Makefile, desktop/package-lock.json, desktop/package.json, desktop/src/renderer/components/app-home/app-home.e2e.ts, desktop/src/renderer/components/app-project/app-project.e2e.ts, desktop/src/renderer/components/app-project/app-project.spec.ts, desktop/src/renderer/components/app-root/app-root.e2e.ts, desktop/src/renderer/components/app-settings/app-settings.e2e.ts, node/Makefile, node/package.json
Sets up continuous integration for desktop.
=> ci(Desktop): Continuous integration setup for desktop

desktop/src/main/document/index.ts, desktop/src/renderer/components.d.ts, desktop/src/renderer/components/app-document/app-document-editor/app-document-editor.css, desktop/src/renderer/components/app-document/app-document-editor/app-document-editor.tsx, desktop/src/renderer/components/app-document/app-document-preview/app-document-preview.css, desktop/src/renderer/components/app-project/app-project-sidebar/app-project-sidebar-file/app-project-sidebar-file.css, desktop/src/renderer/components/app-project/app-project-sidebar/app-project-sidebar-file/app-project-sidebar-file.tsx, desktop/src/renderer/components/app-project/app-project-sidebar/app-project-sidebar-file/iconMap.ts, desktop/src/renderer/components/app-project/app-project-sidebar/app-project-sidebar-files/app-project-sidebar-files.css, desktop/src/renderer/components/app-project/app-project-sidebar/app-project-sidebar-files/app-project-sidebar-files.tsx
- Update editor contents when file changes on disk
- Add collapsible folders to the file tree sidebar
=> Desktop: Document renderer refinements

.ci/azure-pipelines.yml, rust/src/serve.rs
Various additions to try to make builds faster.
=> CI: Rust caching

desktop/Makefile, desktop/src/renderer/components/app-document/app-document-editor/app-document-editor.e2e.ts, desktop/src/renderer/global/app.ts, desktop/stencil.config.ts
This PR attempts to fix test failures on CI
=> test(Desktop): Run tests in CI mode

desktop/package-lock.json, desktop/package.json, desktop/src/main/config/window.ts, desktop/src/main/launcher/window.ts, desktop/src/main/onboarding/window.ts, desktop/src/main/project/window.ts, desktop/src/main/window/index.ts, desktop/src/main/window/security.ts, desktop/src/renderer/components/app-document/app-document-editor/app-document-editor.css, desktop/src/renderer/components/app-document/app-document-editor/app-document-editor.tsx, desktop/src/renderer/components/app-document/app-document-preview/app-document-preview.css, desktop/src/renderer/store/documentPane/documentPaneActions.ts, desktop/src/renderer/store/editorState/editorStateActions.ts, desktop/src/renderer/store/editorState/editorStateSelectors.ts, desktop/src/renderer/store/editorState/editorStateTypes.ts, desktop/src/renderer/store/index.ts
- Keep document history for each document
- Harden security based on best practices
- Add horizontal padding to preview panel
=> Track state/edit history per document

desktop/forge.config.js, desktop/package-lock.json, desktop/package.json, desktop/src/i18n/index.ts, desktop/src/index.ts, desktop/src/main/index.ts, desktop/src/main/menu/index.ts, desktop/src/main/utils/update.ts, desktop/src/main/window/index.ts, desktop/src/preload/errors.ts, desktop/src/preload/utils/env.ts, desktop/src/renderer/global/app.ts, desktop/webpack.main.config.js
close #933
⚠️ This PR should only be merged after the apps are code signed (#931, see #933 for context)
=> feat(Desktop): Add prompt to auto-updating the Desktop client

rust/kernel-python/src/lib.rs, rust/kernel-python/src/python_kernel.py
This  fixes a bug I discovered in which imported modules or functions were not available in functions defined in chunks. The fix comes from using a single context for `exec` and eval`, rather than separate `globals` and `locals`.
=> fix(Python microkernel): Fix issue with availability of imports in functions

desktop/package-lock.json, desktop/package.json, rust/kernels/src/lib.rs, rust/stencila/package-lock.json, rust/stencila/package.json, rust/stencila/src/documents.rs, rust/stencila/src/rpc.rs, themes/package-lock.json, themes/package.json, web/package-lock.json, web/package.json, web/src/documents.ts, web/src/index.ts, web/src/kernels.ts
Before merging this PR, we should merge https://github.com/stencila/designa/pull/285 and update the Components package within `rust/stencila` and `web` directories.
=> feat(Client): Add event listeners for code execution & kernel restart

web/src/client.ts, web/src/index.ts
This enables workflows such as authenticating via request Headers
=> fix(Client): Allow passing through Web Client options

rust/stencila/src/server.rs, web/README.md, web/package.json
Fixes breakages due to changes in packaging of the `web` client module.
=> Fixes web client build and integration with document server

Cargo.lock, rust/cli-utils/Cargo.toml, rust/cli-utils/src/lib.rs, rust/cli-utils/src/result.rs, rust/cli-utils/src/table.rs, rust/cloud/Cargo.toml, rust/cloud/src/cli.rs, rust/cloud/src/cloud.rs, rust/cloud/src/errors.rs, rust/cloud/src/lib.rs, rust/cloud/src/main.rs, rust/cloud/src/orgs.rs, rust/cloud/src/projects.rs, rust/cloud/src/teams.rs, rust/cloud/src/tokens.rs, rust/cloud/src/types.rs, rust/cloud/src/user.rs, rust/cloud/src/users.rs, rust/cloud/src/utils.rs, rust/fs-utils/src/lib.rs, rust/http-utils/src/lib.rs, rust/images/src/change_set.rs, rust/images/src/distribution.rs, rust/images/src/snapshot.rs, rust/images/src/storage.rs, rust/kernel-jupyter/Cargo.toml, rust/kernel-jupyter/src/connection.rs, rust/key-utils/src/lib.rs, rust/stencila/src/config.rs, rust/stencila/src/server.rs
=> Add CLI interfaces for users, organizations and projects and associated types

rust/schema-gen/src/schemas.rs
1. Modify `pub extends: Option<String>` to `pub extends: Option<Vec<String>>`,
and add `#[serde(default)]` and `#[serde(deserialize_with = "handle_string_or_array")]` to support deserialization.
3. Modify `extend` to support multiple inheritance.
4. Modify `expand` to support multiple inheritance.
5. Add handle_string_or_array to ensure compatibility with previous files.
=> feat: #1590 supported multiple inheritance

rust/schema-gen/src/rust.rs
* Simple test
1. Change one yaml file. For example,
Note.yaml -> True.yaml, and `title: Note`->`title: True`
2.  cd `/private/tmp/stencila_patch/rust/schema-gen` && cargo run
3. do a check for change
=> feat: #1593, Extended Rust-KEYWORDS

rust/schema-gen/src/rust.rs, rust/schema-gen/src/schemas.rs, rust/schema/src/types/article.rs, rust/schema/src/types/audio_object.rs, rust/schema/src/types/cite.rs, rust/schema/src/types/claim.rs, rust/schema/src/types/collection.rs, rust/schema/src/types/comment.rs, rust/schema/src/types/contact_point.rs, rust/schema/src/types/creative_work.rs, rust/schema/src/types/datatable.rs, rust/schema/src/types/directory.rs, rust/schema/src/types/figure.rs, rust/schema/src/types/file.rs, rust/schema/src/types/image_object.rs, rust/schema/src/types/media_object.rs, rust/schema/src/types/periodical.rs, rust/schema/src/types/person.rs, rust/schema/src/types/postal_address.rs, rust/schema/src/types/product.rs, rust/schema/src/types/publication_issue.rs, rust/schema/src/types/publication_volume.rs, rust/schema/src/types/review.rs, rust/schema/src/types/software_application.rs, rust/schema/src/types/software_source_code.rs, rust/schema/src/types/table.rs, rust/schema/src/types/video_object.rs
1. replace '\n' to '///' in type, and '    ///' in prop
2. handle case of any_of, make '    ///' back to '///'
> base on #1596
=> Use the original description

Cargo.lock, rust/common/Cargo.toml, rust/common/src/lib.rs, rust/document/src/lib.rs, rust/document/src/sync_file.rs, rust/document/src/sync_string.rs, rust/schema/Cargo.toml, rust/schema/src/traits/node_store/text_value.rs, rust/stencila/Cargo.toml, rust/stencila/src/main.rs
Adds a `sync_string` function similar to `sync_file` but using an in-memory buffer.
=> Sync string

python/README.md
Minor changes to the python Readme to make it runnable.
=> Make python block runnable

node/README.md, package-lock.json, web/README.md
=> docs(web & node): add development docs regarding workspace dependencies

.gitignore, Cargo.lock, rust/agent-anthropic/Cargo.toml, rust/agent-anthropic/src/lib.rs, rust/agents/Cargo.toml, rust/agents/src/lib.rs
=> Add anthropic agent

web/src/languages/markdown/extensions/instructSyntax.ts
** details ** 
Have updated the syntax highlighting for the instruction blocks from using the @@ to the %% %> %% style syntax for inertion and content editing
=> refactor(instructSyntax): change syntax for instruct

web/src/clients/codemirror.ts
**details**
have added a step in the `CodeMirrorClient.sendBufferedOperations()` method, to coalesce consecutive 'insert' operations before sending, code below:
```
this.bufferedOperations = this.bufferedOperations.reduce<FormatOperation[]>(
(ops, current, i) => {
if (i === 0) {
ops.push(current)
} else {
const prev = ops[ops.length - 1]
if (
prev.type === 'insert' &&
current.type === 'insert' &&
+prev.from + prev.insert.length === current.from
) {
ops[ops.length - 1] = {
...prev,
insert: prev.insert + current.insert,
to: current.to,
}
} else {
ops.push(current)
}
}
return ops
},
[]
)
```
nb. the 'selection' update op will still appear in the bufferedOperations, thus break the coalescence up a bit, see the screenshot,
so I can extend the reduce to remove these as well, unless they are …
=> fix(codemirror client): coalesce consecutive insert ops

web/.prettierignore, web/README.md, web/src/ui/selector/index.ts
**Details**
This PR details how we should use tailwind (via twind) to style our web components. In particular, it details how we will deal with long class lists & how we can group them.
=> docs(web): Twind reccomendations

rust/Makefile, rust/kernel-python/ruff.toml, rust/kernel-python/src/kernel.py
PR for #2039 
Clean-up tasks done. This is mostly just tidying, following some sensible rules:
Possible things to do:
- ~~[ ] Replace chained elif with a dictionary/lambdas~~
- ~~[ ] Review the matplotlib status -- it assumes some conventions that I'm not sure are always the case.~~
=> Python kernel review

rust/assistant-anthropic/src/lib.rs, rust/assistant-google/src/lib.rs, rust/assistant-mistral/src/lib.rs, rust/assistant-ollama/src/lib.rs, rust/assistant-openai/src/lib.rs, rust/assistant-specialized/src/lib.rs, rust/assistant/src/lib.rs, rust/assistants/src/cli.rs, rust/assistants/src/lib.rs, rust/assistants/tests/specialized.rs, rust/node-authorship/src/lib.rs, rust/plugins/src/assistants.rs
Rename Assistant properties for consistency with Kernels.
=> refactor(assistants): id->name + name->title

examples/kernels/for-block/assigned-quickjs.md, package-lock.json, web/src/nodes/for-block.ts, web/src/nodes/section.ts, web/src/ui/nodes/properties/iteration-section.ts, web/src/utility/ordinal.ts
This styles component as per designs (well close to them). Currently looks like below. @mike-parkin could you pick this up and fix the following:
=> fix(for loops): style component towards designs

vscode/src/authentication.ts, vscode/src/status-bar.ts
https://github.com/stencila/stencila/issues/2336
=> feat(vscode ext): sign in with access token

web/src/ui/nodes/properties/author/index.ts
**details**
Luckily turned out to be quite a simple fix, 
Just added a position rule to the containing div element and seems to fix the problem.
closes: #2346
=> fix(author): add correct positioning to last-modified tt

vscode/README.md
Add some help text to clarify the different LLM options available to the user.
=> docs(vscode): add some help text for setting up LLM support

rust/publish-ghost/src/lib.rs
adding help heading for ghost publish command like those in zenodo
=> feat(publis ghost): add headings to help message

rust/codec-docx/src/lib.rs, rust/codec-odt/src/lib.rs, rust/codec-pandoc/Cargo.toml, rust/codec-pandoc/src/lib.rs, rust/codec/src/lib.rs, rust/codecs/src/cli.rs
=> codec availability 

Cargo.lock, rust/node-contains/Cargo.toml, rust/node-contains/src/lib.rs, rust/node-execute/Cargo.toml, rust/node-execute/src/if_block.rs, rust/node-execute/src/lib.rs, web/src/nodes/if-block-clause.ts, web/src/ui/buttons/chevron.ts
Related issue https://github.com/stencila/stencila/issues/2562
=> fix(if blocks): assorted fixes related to `IfBlock` nodes

docs/reference/formats/cbor.md, docs/reference/formats/cborzst.md, docs/reference/formats/docx.md, docs/reference/formats/html.md, docs/reference/formats/ipynb.md, docs/reference/formats/jats.md, docs/reference/formats/json.md, docs/reference/formats/json5.md, docs/reference/formats/jsonld.md, docs/reference/formats/lexical.md, docs/reference/formats/markdown.md, docs/reference/formats/md.md, docs/reference/formats/odt.md, docs/reference/formats/pdf.md, docs/reference/formats/qmd.md, docs/reference/formats/smd.md, docs/reference/formats/text.md, docs/reference/formats/yaml.md
merge issues
docs(formats) fixing
adding more that were requested in #2571
=> docs(formats) more formats scaffolded in

.github/workflows/release-cli.yml, .github/workflows/test-rust.yml, .github/workflows/test.yml, rust/Makefile, rust/kernel-kuzu/src/lib.rs, rust/kernel-r/src/lib.rs, rust/schema/tests/sizes.rs
Trying to get tests passing on all platforms.
=> ci: multiplatform tests
